# Data Exploration for the Parkinsons Dataset

In [20]:
import os

import numpy as np

import pandas as pd

from torchvision.datasets.utils import download_url

from sklearn.preprocessing import StandardScaler

## Download the UCI Parkinsons dataset

In [7]:
urls = [
    "https://archive.ics.uci.edu/ml/machine-learning-databases/parkinsons/telemonitoring/parkinsons_updrs.data",
    "https://archive.ics.uci.edu/ml/machine-learning-databases/parkinsons/telemonitoring/parkinsons_updrs.names"
]

raw_folder = "/home/flo/ssdgm/notebooks/datasets/Parkinsons/raw"

os.makedirs(raw_folder, exist_ok=True)

['https://archive.ics.uci.edu/ml/machine-learning-databases/parkinsons/telemonitoring/parkinsons_updrs.data',
 'https://archive.ics.uci.edu/ml/machine-learning-databases/parkinsons/telemonitoring/parkinsons_updrs.names']

In [3]:
filenames = [os.path.basename(url) for url in urls]
filenames

['parkinsons_updrs.data', 'parkinsons_updrs.names']

In [8]:
for filename, url in zip(filenames, urls):
    download_url(url=url, root=raw_folder, filename=filename)

  0%|          | 0/911261 [00:00<?, ?it/s]

  0%|          | 0/4423 [00:00<?, ?it/s]

## Load the UCI Parkinsons dataset

In [14]:
uci_df = pd.read_csv(os.path.join(raw_folder, filenames[0]))

## Load the SSDKL Parkinsons dataset

In [11]:
ssdkl_folder = "/home/flo/ssdgm/notebooks/datasets/SSDKL/parkinsons"

X = np.load(os.path.join(ssdkl_folder, "X.npy"))
y = np.load(os.path.join(ssdkl_folder, "y.npy"))

## Exploration

In [15]:
uci_df.head()

subject#  age  sex  test_time  ...     HNR     RPDE      DFA      PPE
0         1   72    0     5.6431  ...  21.640  0.41888  0.54842  0.16006
1         1   72    0    12.6660  ...  27.183  0.43493  0.56477  0.10810
2         1   72    0    19.6810  ...  23.047  0.46222  0.54405  0.21014
3         1   72    0    25.6470  ...  24.445  0.48730  0.57794  0.33277
4         1   72    0    33.6420  ...  26.126  0.47188  0.56122  0.19361

[5 rows x 22 columns]

In [16]:
uci_df.describe()

subject#          age  ...          DFA          PPE
count  5875.000000  5875.000000  ...  5875.000000  5875.000000
mean     21.494128    64.804936  ...     0.653240     0.219589
std      12.372279     8.821524  ...     0.070902     0.091498
min       1.000000    36.000000  ...     0.514040     0.021983
25%      10.000000    58.000000  ...     0.596180     0.156340
50%      22.000000    65.000000  ...     0.643600     0.205500
75%      33.000000    72.000000  ...     0.711335     0.264490
max      42.000000    85.000000  ...     0.865600     0.731730

[8 rows x 22 columns]

In [18]:
X.shape, y.shape

((5875, 20), (5875,))

In [23]:
np.mean(X, axis=0)

array([-4.06369973e-16, -1.93509511e-17,  3.74924678e-17,  7.74038044e-17,
        1.45132133e-16,  1.16105707e-16, -9.67547555e-18, -2.90264267e-17,
       -4.83773778e-18, -7.74038044e-17, -4.83773778e-17,  4.83773778e-17,
       -2.90264267e-17, -3.87019022e-17,  9.67547555e-17, -2.90264267e-17,
       -6.19230435e-16,  1.93509511e-16,  4.16045449e-16, -4.16045449e-16])

In [24]:
np.std(X, axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [25]:
np.mean(y)

-4.613266742609917e-14

In [26]:
np.std(y)

10.699372551138886

In [28]:
uci_data_npy = uci_df.loc[:, uci_df.columns != "total_UPDRS"].to_numpy()
uci_target_npy = uci_df["total_UPDRS"].to_numpy()

In [30]:
scaler = StandardScaler()

scaler.fit(X=uci_data_npy, y=uci_target_npy)

StandardScaler()

In [37]:
scaled_uci_data = scaler.transform(uci_data_npy)
np.mean(scaled_uci_data, axis=0)


array([ 7.74038044e-17, -4.06369973e-16, -1.93509511e-17,  3.50735989e-17,
        5.80528533e-17,  1.45132133e-16,  1.16105707e-16,  1.93509511e-17,
       -1.93509511e-17,  1.69320822e-16,  1.74158560e-16,  1.83834035e-16,
        4.83773778e-17,  1.54807609e-16, -3.87019022e-17,  9.67547555e-17,
       -3.87019022e-17, -6.38581386e-16,  1.93509511e-16,  4.45071875e-16,
        1.74158560e-16])

In [39]:
np.std(scaled_uci_data, axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1.])